#!/bin/bash
rm out.txt
cargo run --bin noria-zk -- --deployment $1 --clean
rm -r *.db
RUST_BACKTRACE=1 cargo run --release --bin noria-server -- --deployment $1 --verbose &> out.txt
#RUST_BACKTRACE=1 cargo run --bin noria-server -- --deployment $1 --verbose &> out.txt
